services:
  api:
    image: good-growth-api:1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 5000:5000
    volumes:
      - .:/build
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/
  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
  db-client:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMIN_USERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMIN_PASSWORD=${MONGO_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI}
    depends_on:
      - db

volumes:
  mongo-data:
